=== wangshuodong/acsDemo/rms/rms-services/src/main/resources/tpl/BusiTemplate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="unqualified"
	attributeFormDefault="unqualified" targetNamespace="http://www.iot.cn/BusiTemplate"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:busi="http://www.iot.cn/BusiTemplate">

	<!-- root -->
	<xsd:element name="Template" type="busi:BusiTemplate"></xsd:element>

	<!-- 操作模版 整个大的流程 -->
	<xsd:complexType name="BusiTemplate">
		<xsd:all>
			<xsd:element name="OperationFlow" type="busi:OperationFlowType"
				minOccurs="0" maxOccurs="1">
			</xsd:element>
		</xsd:all>
	</xsd:complexType>
	
	<!-- 大的流程包含一个或者多个子流程 -->
	<xsd:complexType name="OperationFlowType">
		<xsd:sequence>
			<xsd:element name="FlowBean" type="busi:FlowBeanType"
				maxOccurs="unbounded" minOccurs="0"></xsd:element>
		</xsd:sequence>
		<!--这个属性表示在整个大流程开始和结束时要做的操作，这个地方用来设置InternetGatewayDevice.X_CMCC_UserInfo.Result的值-->
		<xsd:attribute name="operationReturn" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<!-- 子流程的操作操作步骤 ，它同时包含ADD/SET 等具体的步骤 ... -->
	<xsd:complexType name="FlowBeanType">
		<xsd:sequence>
			<xsd:element name="FlowBeanSearch" type="busi:FlowBeanSearchType"
						 maxOccurs="unbounded" minOccurs="0"></xsd:element>
			<xsd:element name="FlowBeanAdd" type="busi:FlowBeanAddType"
				maxOccurs="unbounded" minOccurs="0"></xsd:element>
			<xsd:element name="FlowBeanSet" type="busi:FlowBeanSetType"
				maxOccurs="unbounded" minOccurs="0"></xsd:element>
		</xsd:sequence>
		<!--FlowBean的唯一标识-->
		<xsd:attribute name="id" type="xsd:string"></xsd:attribute>
		<!--ref表示本流程依赖于某个流程的执行结果-->
		<xsd:attribute name="ref" type="xsd:string"></xsd:attribute>
		<!--refSearch表示本流程依赖于某个查询流程的查询结果，当refSearch和ref同时存在时，会先去取refSearch的结果，如果refSearch的结果不为空，则忽略ref的结果，如果refSearch的结果为空，则去取ref的结果-->
		<xsd:attribute name="refSearch" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<!-- 增加类型的操作步骤 -->
	<xsd:complexType name="FlowBeanSearchType">
		<!--表示属性按顺序出现-->
		<xsd:sequence>
			<!--表示执行查询指令时，传输的参数，默认查询起所有子节点-->
			<xsd:element name="Command" >
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<!--查询结果的匹配定义，支持多个-->
			<xsd:element name="FlowBeanMatch" type="busi:FlowBeanMatchType"
						 maxOccurs="unbounded" minOccurs="0">
			</xsd:element>
			<!-- 需要截取的路径所在的MatchBean的id-->
			<xsd:element name="SplitPath" >
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<!--匹配上的节点进行截取的字符串，查询结果取截取字符串的前半部分，如果不配置该节点，则查询结果直接取匹配上的节点全路径-->
			<xsd:element name="SplitStr" >
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string">
		</xsd:attribute>
	</xsd:complexType>
	<!--匹配类型-->
	<xsd:complexType name="FlowBeanMatchType">
		<xsd:sequence>
			<!--需要匹配的节点的正则表达式-->
			<xsd:element name="Pattern" >
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<!--需要匹配的值-->
			<xsd:element name="MatchValue" >
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<!--当有多个FlowBeanMatch时，用来获取公共路径的截取字符串-->
			<xsd:element name="leaf" >
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string">
		</xsd:attribute>
	</xsd:complexType>
	<!-- 增加类型的操作步骤 -->
	<xsd:complexType name="FlowBeanAddType">
		<xsd:sequence>
			<!--表示执行添加指令时，传输的参数-->
			<xsd:element name="Command" >
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<!--获取参数的键-->
			<xsd:element name="ParamKey" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<!--取默认值-->
			<xsd:element name="Default" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string">
		</xsd:attribute>
		<!--ref表示本流程依赖于某个流程的执行结果-->
		<xsd:attribute name="ref" type="xsd:string">
		</xsd:attribute>
		<!--在添加之前是否先查询，0表示是，1表示否。如果查询到有相应的节点，则不再添加，直接返回查询到的某一个节点-->
		<xsd:attribute name="searchFirst" type="xsd:string"	default="1"></xsd:attribute>
		<!--缓存中查找是否已有,暂时没用-->
		<xsd:attribute name="cached" type="xsd:string"></xsd:attribute>
		<!--refSearch表示本流程依赖于某个查询流程的查询结果，当refSearch和ref同时存在时，会先去取refSearch的结果，如果refSearch的结果不为空，则忽略ref的结果，如果refSearch的结果为空，则去取ref的结果-->
		<xsd:attribute name="refSearch" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<!-- 设置参数 包含有多个参数的设置 -->
	<xsd:complexType name="FlowBeanSetType">
		<xsd:sequence>
			<xsd:element name="SetParam" type="busi:SetParamType"
				maxOccurs="unbounded" minOccurs="1"></xsd:element>
		</xsd:sequence>
		<!--缓存中查找是否已有,暂时没用-->
		<xsd:attribute name="ref" type="xsd:string">
		</xsd:attribute>
		<!--refSearch表示本流程依赖于某个查询流程的查询结果，当refSearch和ref同时存在时，会先去取refSearch的结果，如果refSearch的结果不为空，则忽略ref的结果，如果refSearch的结果为空，则去取ref的结果-->
		<xsd:attribute name="refSearch" type="xsd:string"></xsd:attribute>
		<!--是否需要执行设置操作，isNeedExcute,根据某个FLOW的ID查询FLOW的执行结果，如果执行结果不为空，则不需要执行-->
		<xsd:attribute name="isNeedExcute" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="SetParamType">
		<xsd:sequence>
			<xsd:element name="Command" nillable="true">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="ParamKey" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="DefaultKey" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Default" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<!--stitch表示字符串拼接，表示在ParamKey值后面拼接上stitch的值,stitch和split同时出现时，先执行stitch-->
			<xsd:element name="stitch" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<!--split表示拆分，根据split的值对ParamKey值进行拆分-->
			<xsd:element name="split" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<!--beforeOrAfter表示Command取split的前面(before)的串还是后面(after)的串,和split要成对出现，如果没有beforeOrAfter,默认为before。-->
			<xsd:element name="beforeOrAfter" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<!--参数类型-->
			<xsd:element name="valueType" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== wangshuodong/acsDemo/rms/rms-services/src/main/resources/tpl/PPPoE_Bridged.xml
<?xml version="1.0" encoding="UTF-8"?>
<busi:Template xmlns:busi="http://www.iot.cn/BusiTemplate"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.iot.cn/BusiTemplate BusiTemplate.xsd ">

	<!-- 业务操作流程  D.1. 上行桥连接建立流程-->
	<OperationFlow operationReturn="InternetGatewayDevice.X_CMCC_UserInfo.Result">
		<FlowBean id="PPPoE_Bridged">
			
			<!-- <FlowBeanAdd id="WANDevice">
				<Command>InternetGatewayDevice.WANDevice.</Command>
			</FlowBeanAdd>
			
			<FlowBeanAdd id="WANConnectionDevice" ref="WANDevice">
				<Command>WANConnectionDevice.</Command>
			</FlowBeanAdd>
			
			2.添加实例
			<FlowBeanAdd id="WANPPPConnection" ref="WANConnectionDevice">
				<Command>WANPPPConnection.</Command>
			</FlowBeanAdd> -->
			
			<!-- 1.添加实例 -->
			<FlowBeanAdd id="WANConnectionDevice">
				<Command>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.</Command>
			</FlowBeanAdd>
			<!-- 2.添加实例 -->
			<FlowBeanAdd id="WANPPPConnection" ref="WANConnectionDevice">
				<Command>WANPPPConnection.</Command>
			</FlowBeanAdd>
			
			<!-- 3.设置参数 -->
			<FlowBeanSet ref="WANPPPConnection">
				<SetParam>
					<Command>X_CMCC_VLANMode</Command>
					<ParamKey>X_CMCC_VLANMode</ParamKey>
				</SetParam>
				<SetParam>
					<Command>X_CMCC_VLANIDMark</Command>
					<ParamKey>X_CMCC_VLANIDMark</ParamKey>
				</SetParam>
				<SetParam>
					<Command>ConnectionType</Command>
					<Default>PPPoE_Bridged</Default>
				</SetParam>
				<SetParam>
					<Command>X_CMCC_LanInterface</Command>
					<ParamKey>X_CMCC_LanInterface</ParamKey>
				</SetParam>
				<SetParam>
					<Command>X_CMCC_ServiceList</Command>
					<ParamKey>X_CMCC_ServiceList</ParamKey>
				</SetParam>
				<SetParam>
					<Command>Enable</Command>
					<Default>1</Default>
				</SetParam>
			</FlowBeanSet>
		</FlowBean>
	</OperationFlow>
</busi:Template>

=== wangshuodong/acsDemo/rms/rms-services/src/main/resources/tpl/OTT.xml
<?xml version="1.0" encoding="UTF-8"?>
<busi:Template xmlns:busi="http://www.iot.cn/BusiTemplate"
			   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			   xsi:schemaLocation="http://www.iot.cn/BusiTemplate BusiTemplate.xsd ">

	<!-- 业务操作流程  D.4. OTT业务下发流程-->
	<OperationFlow operationReturn="InternetGatewayDevice.X_CMCC_UserInfo.Result">
		<!-- 1.	按附录D.2创建1个INTERNET类型的WAN，作为上网WAN连接。 -->
		<FlowBean id="INTERNET_PPPoE_Routed">

			<!--查询节点值实例-->
			<FlowBeanSearch id="INTERNETWAN">
				<!--查询根节点-->
				<Command>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.</Command>
				<FlowBeanMatch id ="X_CMCC_ServiceList">
					<!--匹配正则表达式-->
					<Pattern>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.[0-9]+.WANPPPConnection.[0-9]+.X_CMCC_ServiceList</Pattern>
					<!--匹配的值-->
					<MatchValue>INTERNET</MatchValue>
					<leaf>X_CMCC_ServiceList</leaf>
				</FlowBeanMatch>
				<FlowBeanMatch id ="X_CMCC_VLANIDMark">
					<!--匹配正则表达式-->
					<Pattern>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.[0-9]+.WANPPPConnection.[0-9]+.X_CMCC_VLANIDMark</Pattern>
					<!--匹配的值-->
					<MatchValue>41</MatchValue>
					<leaf>X_CMCC_VLANIDMark</leaf>
				</FlowBeanMatch>
				<!--节点截取的依据串-->
				<SplitPath>X_CMCC_ServiceList</SplitPath><!-- 需要截取的路径所在的MatchBean的id-->
				<SplitStr>X_CMCC_ServiceList</SplitStr>

			</FlowBeanSearch>

			<!--如果refSearch查询到节点了，则本FlowBeanAdd不执行-->
			<FlowBeanAdd id="INTERNET_WANConnectionDevice" refSearch="INTERNETWAN" searchFirst="0">
				<Command>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.</Command>
			</FlowBeanAdd>

			<!--如果refSearch查询到节点了，则本FlowBeanAdd不执行-->
			<FlowBeanAdd id="INTERNET_WANPPPConnection" ref="INTERNET_WANConnectionDevice" refSearch="INTERNETWAN" >
				<Command>WANPPPConnection.</Command>
			</FlowBeanAdd>
			<!--isNeedExcute,根据某个FLOW的ID查询FLOW的执行结果，如果执行结果不为空，则不需要执行-->
			<FlowBeanSet ref="INTERNET_WANPPPConnection" refSearch="INTERNETWAN" isNeedExcute ="INTERNETWAN">
				<SetParam>
					<!--2表示重写VLAN-->
					<Command>X_CMCC_VLANMode</Command>
					<Default>2</Default>
				</SetParam>
				<SetParam>
					<!--某个省的VLANID应该是固定的，41是安徽的-->
					<Command>X_CMCC_VLANIDMark</Command>
					<Default>41</Default>
				</SetParam>
				<SetParam>
					<Command>ConnectionType</Command>
					<Default>PPPoE_Routed</Default>
				</SetParam>
				<SetParam>
					<Command>Username</Command>
					<ParamKey>Username</ParamKey>
				</SetParam>
				<SetParam>
					<Command>Password</Command>
					<ParamKey>Password</ParamKey>
				</SetParam>
				<!--<SetParam>
					<Command>X_CMCC_LanInterface</Command>
					<ParamKey>INTERNET_X_CMCC_LanInterface</ParamKey>
				</SetParam>-->
				<SetParam>
					<Command>X_CMCC_ServiceList</Command>
					<Default>INTERNET</Default>
				</SetParam>
				<SetParam>
					<Command>Enable</Command>
					<Default>1</Default>
				</SetParam>
			</FlowBeanSet>
		</FlowBean>

		<!-- 2.	按附录D.2/D.3创建1个OTHER类型的WAN，作为OTT业务的WAN连接。 -->
		<FlowBean id="OTHER_PPPoE_Routed">
			<!-- <FlowBeanAdd id="OTHER_WANDevice">
				<Command>InternetGatewayDevice.WANDevice.</Command>
			</FlowBeanAdd> -->
			<!--查询节点值实例-->
			<FlowBeanSearch id="OTHERWAN">
				<!--查询根节点-->
				<Command>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.</Command>
				<FlowBeanMatch id ="X_CMCC_ServiceList">
					<!--匹配正则表达式-->
					<Pattern>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.[0-9]+.WANPPPConnection.[0-9]+.X_CMCC_ServiceList</Pattern>
					<!--匹配的值-->
					<MatchValue>OTHER</MatchValue>
					<leaf>X_CMCC_ServiceList</leaf>
				</FlowBeanMatch>
				<FlowBeanMatch id ="X_CMCC_VLANIDMark">
					<!--匹配正则表达式-->
					<Pattern>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.[0-9]+.WANPPPConnection.[0-9]+.X_CMCC_VLANIDMark</Pattern>
					<!--匹配的值-->
					<MatchValue>41</MatchValue>
					<leaf>X_CMCC_VLANIDMark</leaf>
				</FlowBeanMatch>
				<!--节点截取的依据串-->
				<SplitPath>X_CMCC_ServiceList</SplitPath><!-- 需要截取的路径所在的MatchBean的id-->
				<SplitStr>X_CMCC_ServiceList</SplitStr>
			</FlowBeanSearch>

			<FlowBeanAdd id="OTHER_WANConnectionDevice" searchFirst="0" refSearch="OTHERWAN">
				<Command>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.</Command>
			</FlowBeanAdd>

			<!-- 2.添加实例 -->
			<FlowBeanAdd id="OTHER_WANPPPConnection" ref="OTHER_WANConnectionDevice" refSearch="OTHERWAN">
				<Command>WANPPPConnection.</Command>
			</FlowBeanAdd>

			<!-- 3.设置参数 -->
			<FlowBeanSet ref="OTHER_WANPPPConnection" refSearch="OTHERWAN">
				<SetParam>
					<!--2表示重写VLAN-->
					<Command>X_CMCC_VLANMode</Command>
					<Default>2</Default>
				</SetParam>
				<SetParam>
					<!--某个省的VLANID应该是固定的，41是安徽的-->
					<Command>X_CMCC_VLANIDMark</Command>
					<Default>41</Default>
				</SetParam>
				<SetParam>
					<Command>ConnectionType</Command>
					<Default>PPPoE_Routed</Default>
				</SetParam>
				<SetParam>
					<Command>Username</Command>
					<ParamKey>Username</ParamKey>
				</SetParam>
				<SetParam>
					<Command>Password</Command>
					<ParamKey>Password</ParamKey>
				</SetParam>
				<!--<SetParam>
					<Command>X_CMCC_LanInterface</Command>
					<ParamKey>OTHER_X_CMCC_LanInterface</ParamKey>
				</SetParam>-->
				<SetParam>
					<Command>X_CMCC_ServiceList</Command>
					<Default>OTHER</Default>
				</SetParam>
				<SetParam>
					<Command>Enable</Command>
					<Default>1</Default>
				</SetParam>
			</FlowBeanSet>
		</FlowBean>

		<!-- 3.	设置默认路由 InternetGatewayDevice.Layer3Forwarding.DefaultConnectionService =（INTERNET WAN路径） -->
		<FlowBean>
			<FlowBeanSet >
				<SetParam>
					<Command>InternetGatewayDevice.Layer3Forwarding.DefaultConnectionService</Command>
					<!--配置FlowBean的ID，表示取这个FlowBean的最终执行结果，最后一步执行结果不为空的结果值-->
					<ParamKey>INTERNET_PPPoE_Routed</ParamKey>
				</SetParam>
			</FlowBeanSet>
		</FlowBean>

		<!-- 4.	增加实例InternetGatewayDevice.Layer3Forwarding.Forwarding.{i}. 实例 -->
		<FlowBean >
			<FlowBeanAdd id="Forwarding">
				<Command>InternetGatewayDevice.Layer3Forwarding.Forwarding.</Command>
			</FlowBeanAdd>

			<!-- 3.设置参数 -->
			<FlowBeanSet ref="Forwarding">
				<SetParam>
					<!--OTT服务器IP-->
					<Command>DestIPAddress</Command>
					<Default>192.168.1.2</Default>
				</SetParam>
				<SetParam>
					<!--OTT服务器掩码-->
					<Command>DestSubnetMask</Command>
					<Default>255.255.0.0</Default>
				</SetParam>
				<SetParam>
					<Command>Interface</Command>
					<!--配置FlowBean的ID，表示取这个FlowBean的最终执行结果，最后一步执行结果不为空的结果值-->
					<ParamKey>OTHER_PPPoE_Routed</ParamKey>
				</SetParam>
			</FlowBeanSet>
		</FlowBean>
	</OperationFlow>
</busi:Template>

=== wangshuodong/acsDemo/rms/rms-services/src/main/resources/tpl/VoIP.xml
<?xml version="1.0" encoding="UTF-8"?>
<busi:Template xmlns:busi="http://www.iot.cn/BusiTemplate"
			   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			   xsi:schemaLocation="http://www.iot.cn/BusiTemplate BusiTemplate.xsd ">

	<!-- 业务操作流程  D.5. VoIP业务开通流程-->
	<OperationFlow operationReturn="InternetGatewayDevice.X_CMCC_UserInfo.Result">

		<FlowBean id="PPPoE_Routed">
			<!--查询节点值实例-->
			<FlowBeanSearch id="VOIPWAN">
				<!--查询根节点-->
				<Command>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.</Command>
				<FlowBeanMatch id ="X_CMCC_ServiceList">
					<!--匹配正则表达式-->
					<Pattern>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.[0-9]+.WANIPConnection.[0-9]+.X_CMCC_ServiceList</Pattern>
					<!--匹配的值-->
					<MatchValue>VOIP</MatchValue>
					<leaf>X_CMCC_ServiceList</leaf>
				</FlowBeanMatch>
				<!--节点截取的依据串-->
				<SplitPath>X_CMCC_ServiceList</SplitPath><!-- 需要截取的路径所在的MatchBean的id-->
				<SplitStr>X_CMCC_ServiceList</SplitStr>

			</FlowBeanSearch>


			<!-- 1.添加实例 -->
			<FlowBeanAdd id="WANConnectionDevice" refSearch="VOIPWAN" searchFirst="0">
				<Command>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.</Command>
			</FlowBeanAdd>
			<!-- 2.添加实例 -->
			<FlowBeanAdd id="WANIPConnection" ref="WANConnectionDevice" refSearch="VOIPWAN" >
				<Command>WANIPConnection.</Command>
			</FlowBeanAdd>

			<!-- 3.设置参数 -->
			<FlowBeanSet ref="WANIPConnection" refSearch="VOIPWAN">
				<SetParam>
					<!--2表示重写VLAN-->
					<Command>X_CMCC_VLANMode</Command>
					<Default>2</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<!--某个省的VLANID应该是固定的，47是安徽的-->
					<Command>X_CMCC_VLANIDMark</Command>
					<Default>47</Default>
					<valueType>int</valueType>
				</SetParam>
				<SetParam>
					<Command>ConnectionType</Command>
					<Default>IP_Routed</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>AddressingType</Command>
					<Default>DHCP</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>X_CMCC_802-1pMark</Command>
					<Default>5</Default>
					<valueType>string</valueType>
				</SetParam>
				<!--<SetParam>
					<Command>X_CMCC_LanInterface</Command>
					<ParamKey>X_CMCC_LanInterface</ParamKey>
				</SetParam>-->
				<!--表示VOIP的WAN连接-->
				<SetParam>
					<Command>X_CMCC_ServiceList</Command>
					<Default>VOIP</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>Enable</Command>
					<Default>true</Default>
					<valueType>boolean</valueType>
				</SetParam>
			</FlowBeanSet>
		</FlowBean>

		<!-- 子流程 -->
		<FlowBean>
			<!-- 1.添加实例 -->
			<FlowBeanAdd id="VoiceService" searchFirst="0" >
				<Command>InternetGatewayDevice.Services.VoiceService.</Command>
			</FlowBeanAdd>

			<FlowBeanAdd id="VoiceProfile" ref="VoiceService" searchFirst="0">
				<Command>VoiceProfile.</Command>
			</FlowBeanAdd>

			<!-- 3.设置参数 -->
			<FlowBeanSet ref="VoiceProfile">
				<SetParam>
					<Command>X_CMCC_ServerType</Command>
					<Default>0</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>SIP.ProxyServer</Command>
					<Default>211.138.185.97</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>SIP.ProxyServerPort</Command>
					<Default>5060</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>SIP.X_CMCC_Standby-ProxyServer</Command>
					<Default>211.138.185.97</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>SIP.X_CMCC_Standby-ProxyServerPort</Command>
					<Default>5060</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>SIP.RegistrarServer</Command>
					<Default>ims.ah.chinamobile.com</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>SIP.RegistrarServerPort</Command>
					<Default>5060</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>SIP.X_CMCC_Standby-RegistrarServer</Command>
					<Default>211.138.185.97</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>SIP.X_CMCC_Standby-RegistrarServerPort</Command>
					<Default>5060</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>SIP.OutboundProxy</Command>
					<Default>211.138.185.97</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>SIP.OutboundProxyPort</Command>
					<Default>5060</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>SIP.X_CMCC_Standby-OutboundProxy</Command>
					<Default>211.138.185.97</Default>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>SIP.X_CMCC_Standby-OutboundProxyPort</Command>
					<Default>5060</Default>
					<valueType>string</valueType>
				</SetParam>
			</FlowBeanSet>
		</FlowBean>

		<FlowBean>
			<!-- 1.添加实例 -->
			<FlowBeanAdd id="Line" ref="VoiceProfile" searchFirst="0">
				<Command>Line.</Command>
			</FlowBeanAdd>

			<!-- 3.设置参数 -->
			<FlowBeanSet ref="Line">
				<SetParam>
					<Command>SIP.AuthUserName</Command>
					<ParamKey>SIP.AuthUserName</ParamKey>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>SIP.AuthPassword</Command>
					<ParamKey>SIP.AuthPassword</ParamKey>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<!--用户标识，通常为用户电话号码-->
					<Command>SIP.URI</Command>
					<ParamKey>SIP.AuthUserName</ParamKey>

					<!--stitch表示字符串拼接，表示在ParamKey值后面拼接上stitch的值,stitch和split同时出现时，先执行stitch-->
					<!--<stitch>@ims.ah.chinamobile.com</stitch>-->
					<!--split表示拆分，根据split的值对ParamKey值进行拆分-->
					<split>@</split>
					<!--beforeOrAfter表示Command取split的前面(before)的串还是后面(after)的串,和split要成对出现，如果没有beforeOrAfter,默认为before。-->
					<beforeOrAfter>before</beforeOrAfter>
					<valueType>string</valueType>
				</SetParam>
				<SetParam>
					<Command>Enable</Command>
					<Default>Enabled</Default>
					<valueType>string</valueType>
				</SetParam>
			</FlowBeanSet>
		</FlowBean>
	</OperationFlow>
</busi:Template>

=== wangshuodong/acsDemo/rms/rms-services/src/main/resources/tpl/PPPoE_Routed.xml
<?xml version="1.0" encoding="UTF-8"?>
<busi:Template xmlns:busi="http://www.iot.cn/BusiTemplate"
			   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			   xsi:schemaLocation="http://www.iot.cn/BusiTemplate BusiTemplate.xsd ">

	<!-- 业务操作流程 D.2. 上行路由连接PPPoE模式建立流程-->
	<OperationFlow operationReturn="InternetGatewayDevice.X_CMCC_UserInfo.Result">
		<FlowBean id="PPPoE_Routed">
			<!-- 1.添加实例 -->
			<!-- <FlowBeanAdd id="WANDevice">
				<Command>InternetGatewayDevice.WANDevice.</Command>
			</FlowBeanAdd>
			
			<FlowBeanAdd id="WANConnectionDevice" ref="WANDevice">
				<Command>WANConnectionDevice.</Command>
			</FlowBeanAdd>
			
			2.添加实例
			<FlowBeanAdd id="WANPPPConnection" ref="WANConnectionDevice">
				<Command>WANPPPConnection.</Command>
			</FlowBeanAdd> -->
			<!--查询节点值实例-->
			<FlowBeanSearch id="INTERNETWAN">
				<!--查询根节点-->
				<Command>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.</Command>
				<FlowBeanMatch id ="X_CMCC_ServiceList">
					<!--匹配正则表达式-->
					<Pattern>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.[0-9]+.WANPPPConnection.[0-9]+.X_CMCC_ServiceList</Pattern>
					<!--匹配的值-->
					<MatchValue>INTERNET</MatchValue>
					<leaf>X_CMCC_ServiceList</leaf>
				</FlowBeanMatch>
				<!--节点截取的依据串-->
				<SplitPath>X_CMCC_ServiceList</SplitPath><!-- 需要截取的路径所在的MatchBean的id-->
				<SplitStr>X_CMCC_ServiceList</SplitStr>

			</FlowBeanSearch>

			<!-- 1.添加实例 -->
			<!--如果refSearch查询到节点了，则本FlowBeanAdd不执行-->
			<FlowBeanAdd id="WANConnectionDevice" refSearch="INTERNETWAN" searchFirst="0">
				<Command>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.</Command>
			</FlowBeanAdd>
			<!-- 2.添加实例 -->
			<FlowBeanAdd id="WANPPPConnection" ref="WANConnectionDevice" refSearch="INTERNETWAN" >
				<Command>WANPPPConnection.</Command>
			</FlowBeanAdd>

			<!-- 3.设置参数 -->
			<!--如果refSearch查询到节点了，则设置参数的路径取refSearch获取到的路径-->
			<FlowBeanSet ref="WANPPPConnection" refSearch="INTERNETWAN">
				<SetParam>
					<!--2表示重写VLAN-->
					<Command>X_CMCC_VLANMode</Command>
					<Default>2</Default>
				</SetParam>
				<SetParam>
					<!--某个省的VLANID应该是固定的，41是安徽的-->
					<Command>X_CMCC_VLANIDMark</Command>
					<Default>41</Default>
				</SetParam>
				<SetParam>
					<Command>ConnectionType</Command>
					<Default>PPPoE_Routed</Default>
				</SetParam>
				<SetParam>
					<Command>Username</Command>
					<ParamKey>Username</ParamKey>
				</SetParam>
				<SetParam>
					<Command>Password</Command>
					<ParamKey>Password</ParamKey>
				</SetParam>
				<!--<SetParam>
					<Command>X_CMCC_LanInterface</Command>
					<ParamKey>X_CMCC_LanInterface</ParamKey>
				</SetParam>-->
				<!--表示INTERNET的WAN连接-->
				<SetParam>
					<Command>X_CMCC_ServiceList</Command>
					<Default>INTERNET</Default>
				</SetParam>
				<SetParam>
					<Command>Enable</Command>
					<Default>true</Default>
				</SetParam>
			</FlowBeanSet>
		</FlowBean>
	</OperationFlow>
</busi:Template>
